name: Ron Becker
description: Just Another Geek on the Internet!
meta_description: "The personal blog of another geek on the internet."

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl:
domain_name: "http://sparrowharkproject.github.io"
google_analytics: "UA-XXXXXXXX-X"
plugins: [jekyll-paginate]

# Details for the RSS feed generator
url: ""
author: "Ron Becker"

# Disqus config
disqus-shortname: "theronbecker"
